RoR/scoring-isdb/config/routes.rb
Rails.application.routes.draw do    
  resources :grant_sectors

  match 'proposal_assessment_summaries/:proposal_id' => 'proposal_assessment_summaries#complete', :as => :complete_assessment, :via => :patch
  match 'proposal_assessment_summaries/:proposal_id/:user_id' => 'proposal_assessment_summaries#reset_assessment', :as => :reset_eval_assessment, :via => :patch
  match 'grants/:grant_id/reset_grant' => 'grants#reset_grant', :as => :reset_grant, :via => :patch
  
  match 'active_grant_sectors/all/gs_edit' => 'grant_sectors#gs_edit_all', :as => :gs_edit_all, :via => :get
  match 'active_grant_sectors/gs_all' => 'grant_sectors#gs_update_all', :as => :gs_update_all, :via => :put

  match 'proposals/select_winners' => 'proposals#update_selection', :as => :select_winners, :via => :put

  resources :funds
  resources :fund_sources
  resources :localities
  resources :proposals do
    resources :geographic_coverages, :budgets, :funds
    member do
      patch :complete
    end
  end

  resources :development_goals
  resources :sectors
  resources :provinces

  match 'home' => 'home#home_index', :as => :home, :via => :get
  match 'reports' => 'reports#index', :as => :reports, :via => :get
  match 'reports/statistics' => 'reports#statistics', :as => :reports_statistics, :via => :get
  match 'reports/assessments_mark_order' => 'reports#assessments_mark_order', :as => :reports_assessments_mark_order, :via => :get
  match 'reports/assessments_province_order' => 'reports#assessments_province_order', :as => :reports_assessments_province_order, :via => :get
  match 'reports/assessments_report/:proposal_id' => 'reports#assessments_rep', :as => :assessments_rep, :via => :get

  devise_for :users, except: [:new, :update]
  devise_scope :user do
    get "users/sign_up", to: "users/registrations#new", as: "new_app_user"
    put "/app_users/:id", to: "users/registrations#update", as: "update_app_user"
    patch "/app_users/:id", to: "users/registrations#update"
  end 

  as :user do
    get "/users", to: "registrations#admin_index", as: "admin_users"
    post "/add_user", to: "registrations#create", as: "create_user"
    get "/users/new", to: "registrations#admin_new", as: "admin_new_user"
    get "/users/admin_edit/:id", to: "registrations#admin_edit", as: "admin_edit_user"
    get "/admin_users/:id", to: "registrations#admin_show", as: "show_user"
    put "/users/:id", to: "registrations#update", as: "update_user"
    patch "/users/:id", to: "registrations#update"
    
  end

  resources :grants do
    member do
      patch :close
    end
  end

  resources :assessments 
  
  resources :categories
  resources :criterions do
    resources :criterion_details 
  end
  
  match 'e_assessments/edit/:proposal_id' => 'assessments#edit_all', :as => :edit_all, :via => :get 

  match 'e_assessments/update_all' => 'assessments#update_all', :as => :update_all, :via => :put 

  match 'users/:id/add_proposal' => 'proposals#add_proposal', :as => :add_proposal, :via => :post

  match 'proposals/:id' => 'proposals#update', :as => :add_geographic_coverage, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_budget, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_fund, :via => :post

  

  root to: "home#home_index"

  get '*a', :to => "home#home_index"

end

RoR/scoring-isdb/app/models/criterion_detail.rb
class CriterionDetail < ActiveRecord::Base
	
	has_many :assessment_criterion_details, :dependent => :destroy
    has_many :assessments, :through => :assessment_criterion_details

    accepts_nested_attributes_for :assessment_criterion_details, 
                                :reject_if => :all_blank


  def weight_with_description
    "#{description} ... (#{weight.to_i})"
  end
                          
end

RoR/scoring-isdb/app/controllers/criterion_details_controller.rb
class CriterionDetailsController < ApplicationController
  before_action :set_criterion_detail, only: [:show, :edit, :update, :destroy]
  before_action :check_privs
  
  # GET /criterion_details
  # GET /criterion_details.json
  def index
    @criterion = Criterion.find(params[:criterion_id])
    @criterion_details = @criterion.criterion_details.all #CriterionDetail.where("criterion_id=?", params[:criterion_id]) #@criterion.criterion_details.all
  end
  # GET /criterion_details/1
  # GET /criterion_details/1.json
  def show
  end

  # GET /criterion_details/new
  def new
    @criterion = Criterion.find(params[:criterion_id])
    @criterion_detail = CriterionDetail.new
  end

  # GET /criterion_details/1/edit
  def edit
  end

  # POST /criterion_details
  # POST /criterion_details.json
  def create
    @criterion_detail = CriterionDetail.new(criterion_detail_params)

    respond_to do |format|
      if @criterion_detail.save
        format.html { redirect_to criterion_criterion_details_path, notice: 'تم إضافة مقياس بنجاح' }
        format.json { render :show, status: :created, location: @criterion_detail }
      else
        format.html { render :new }
        format.json { render json: @criterion_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterion_details/1
  # PATCH/PUT /criterion_details/1.json
  #criterion_criterion_details_path
  def update
    respond_to do |format|
      if @criterion_detail.update(criterion_detail_params)
        format.html { redirect_to criterion_criterion_details_path, notice: 'تم تعديل المقياس بنجاح' }
        format.json { render :show, status: :ok, location: @criterion_detail }
      else
        format.html { render :edit }
        format.json { render json: @criterion_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterion_details/1
  # DELETE /criterion_details/1.json
  def destroy
    @criterion_detail.destroy
    respond_to do |format|
      format.html { redirect_to criterion_criterion_details_path, notice: 'تم حذف المقياس بنجاح' }
      format.json { head :no_content }
    end
  end

  private
    def check_privs
      if !(current_user.is_admin?)
        respond_to do |format|
          format.html { redirect_to '/', alert: 'Insufficient Privileges..' } unless current_user.is_admin?
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion_detail
      #@criterion_detail = CriterionDetail.find(params[:id])
      @criterion = Criterion.find(params[:criterion_id])
      @criterion_detail = CriterionDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterion_detail_params
      params.require(:criterion_detail).permit(:description, :weight, :is_active, :criterion_id)
    end
end

RoR/scoring-isdb/app/helpers/criterion_details_helper.rb
module CriterionDetailsHelper
end

RoR/scoring-isdb/app/views/criterion_details/_form.html.erb
<%= simple_form_for ([@criterion, @criterion_detail]), :html => { :class => "form-horizontal criterion_detail" } do |f| %>

    <% if @criterion_detail.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@criterion_detail.errors.count, "error") %> prohibited this criterion_detail from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @criterion_detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    الوصف
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@criterion_detail[:description]) %>
  </div>
  <div class="control-group">
    الوزن
    <div class="controls">
      <%= f.text_field :weight, :class => 'form-control' %>
    </div>
    <%= error_span(@criterion_detail[:weight]) %>
  </div>
  <div class="control-group">
    رقم المعيار
    <div class="controls">
      <%= f.text_field :criterion_id, :class => 'form-control' %>
    </div>
    <%= error_span(@criterion_detail[:criterion_id]) %>
  </div>
  <div class="row">
    <div class="funkyradio funkyradio-info pull-right">
      <%= f.check_box :is_active, :id => 'submit' %>
      <%= f.label :is_active, "فعال؟", :for => "submit" %>
      <%= error_span(@criterion_detail[:is_active]) %>
    </div> 
  </div> 

  <br/>
  <div class="row">
    <%= f.submit "حفظ", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              criterion_criterion_details_path, :class => 'btn btn-default' %>
  </div>
  

<% end %>

RoR/scoring-isdb/app/views/criterion_details/edit.html.erb
<%- model_class = CriterionDetail -%>
<div class="page-header">
  <h1>تعديل المقياس</h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/criterion_details/index.html.erb
<%- model_class = CriterionDetail -%>
<div class="jumbotron">
    <h2 style="font-family: 'Droid Arabic Kufi';">المقاييس</h2>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>الوصف</th>
      <th>الوزن</th>
      <th>المعيار</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @criterion_details.each do |criterion_detail| %>
      <tr>
        <td><%= link_to criterion_detail.description, criterion_criterion_detail_path(criterion_detail.criterion_id, criterion_detail.id) %></td>
        <td><%= criterion_detail.weight %></td>
        <td><%= criterion_detail.criterion_id %>-<%= Criterion.find(criterion_detail.criterion_id).description %></td>
        <td>
          <%= link_to edit_criterion_criterion_detail_path(@criterion.id, criterion_detail.id),:method => :get do %>
          <i class="fa fa-edit fa-lg"></i>
          <% end %>
          &nbsp;&nbsp;&nbsp;  
          <%= link_to criterion_criterion_detail_path(criterion_detail.criterion_id, criterion_detail.id),
                      :method => :delete, 
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
                      <i class="fa fa-trash-o fa-lg"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to new_criterion_criterion_detail_path,
            :class => 'btn btn-info'  do %>
            إضافة مقياس جديد
        <i class="fa fa-plus-circle"></i>
<% end %>  

RoR/scoring-isdb/app/views/criterion_details/new.html.erb
<%- model_class = CriterionDetail -%>
<div class="page-header">
  <h1>مقياس جديد</h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/criterion_details/show.html.erb
<%- model_class = CriterionDetail -%>
<div class="page-header">
  <h1>المقياس</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>الوصف:</strong></dt>
  <dd><%= @criterion_detail.description %></dd>
  <dt><strong>الوزن:</strong></dt>
  <dd><%= @criterion_detail.weight %></dd>
  <dt><strong>المعيار:</strong></dt>
  <dd><%= @criterion_detail.criterion_id %>-<%= Criterion.find(@criterion_detail.criterion_id).description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              criterions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_criterion_criterion_detail_path(@criterion_detail.criterion_id, @criterion_detail.id), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              criterion_criterion_detail_path(@criterion_detail.id, @criterion_detail.criterion_id),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>