RoR/scoring-isdb/config/routes.rb
Rails.application.routes.draw do    
  resources :grant_sectors

  match 'proposal_assessment_summaries/:proposal_id' => 'proposal_assessment_summaries#complete', :as => :complete_assessment, :via => :patch
  match 'proposal_assessment_summaries/:proposal_id/:user_id' => 'proposal_assessment_summaries#reset_assessment', :as => :reset_eval_assessment, :via => :patch
  match 'grants/:grant_id/reset_grant' => 'grants#reset_grant', :as => :reset_grant, :via => :patch
  
  match 'active_grant_sectors/all/gs_edit' => 'grant_sectors#gs_edit_all', :as => :gs_edit_all, :via => :get
  match 'active_grant_sectors/gs_all' => 'grant_sectors#gs_update_all', :as => :gs_update_all, :via => :put

  match 'proposals/select_winners' => 'proposals#update_selection', :as => :select_winners, :via => :put

  resources :funds
  resources :fund_sources
  resources :localities
  resources :proposals do
    resources :geographic_coverages, :budgets, :funds
    member do
      patch :complete
    end
  end

  resources :development_goals
  resources :sectors
  resources :provinces

  match 'home' => 'home#home_index', :as => :home, :via => :get
  match 'reports' => 'reports#index', :as => :reports, :via => :get
  match 'reports/statistics' => 'reports#statistics', :as => :reports_statistics, :via => :get
  match 'reports/assessments_mark_order' => 'reports#assessments_mark_order', :as => :reports_assessments_mark_order, :via => :get
  match 'reports/assessments_province_order' => 'reports#assessments_province_order', :as => :reports_assessments_province_order, :via => :get
  match 'reports/assessments_report/:proposal_id' => 'reports#assessments_rep', :as => :assessments_rep, :via => :get

  devise_for :users, except: [:new, :update]
  devise_scope :user do
    get "users/sign_up", to: "users/registrations#new", as: "new_app_user"
    put "/app_users/:id", to: "users/registrations#update", as: "update_app_user"
    patch "/app_users/:id", to: "users/registrations#update"
  end 

  as :user do
    get "/users", to: "registrations#admin_index", as: "admin_users"
    post "/add_user", to: "registrations#create", as: "create_user"
    get "/users/new", to: "registrations#admin_new", as: "admin_new_user"
    get "/users/admin_edit/:id", to: "registrations#admin_edit", as: "admin_edit_user"
    get "/admin_users/:id", to: "registrations#admin_show", as: "show_user"
    put "/users/:id", to: "registrations#update", as: "update_user"
    patch "/users/:id", to: "registrations#update"
    
  end

  resources :grants do
    member do
      patch :close
    end
  end

  resources :assessments 
  
  resources :categories
  resources :criterions do
    resources :criterion_details 
  end
  
  match 'e_assessments/edit/:proposal_id' => 'assessments#edit_all', :as => :edit_all, :via => :get 

  match 'e_assessments/update_all' => 'assessments#update_all', :as => :update_all, :via => :put 

  match 'users/:id/add_proposal' => 'proposals#add_proposal', :as => :add_proposal, :via => :post

  match 'proposals/:id' => 'proposals#update', :as => :add_geographic_coverage, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_budget, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_fund, :via => :post

  

  root to: "home#home_index"

  get '*a', :to => "home#home_index"

end

RoR/scoring-isdb/app/models/criterion.rb
class Criterion < ActiveRecord::Base
	belongs_to :category
	has_many :criterion_details
	has_many :assessments
end

RoR/scoring-isdb/app/controllers/criterions_controller.rb
class CriterionsController < ApplicationController
  before_action :set_criterion, only: [:show, :edit, :update, :destroy]
  before_action :check_privs
  
  # GET /criterions
  # GET /criterions.json
  def index
    @criterions = Criterion.all.order(:id)
  end

  # GET /criterions/1
  # GET /criterions/1.json
  def show
  end

  # GET /criterions/new
  def new
    @criterion = Criterion.new
  end

  # GET /criterions/1/edit
  def edit
  end

  # POST /criterions
  # POST /criterions.json
  def create
    @criterion = Criterion.new(criterion_params)

    respond_to do |format|
      if @criterion.save
        format.html { redirect_to criterions_path, notice: 'تم إضافة معيار بنجاح' }
        format.json { render :show, status: :created, location: @criterion }
      else
        format.html { render :new }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criterions/1
  # PATCH/PUT /criterions/1.json
  def update
    respond_to do |format|
      if @criterion.update(criterion_params)
        format.html { redirect_to @criterion, notice: 'تم تعديل معيار بنجاح' }
        format.json { render :show, status: :ok, location: @criterion }
      else
        format.html { render :edit }
        format.json { render json: @criterion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criterions/1
  # DELETE /criterions/1.json
  def destroy
    @criterion.destroy
    respond_to do |format|
      format.html { redirect_to criterions_url, notice: 'تم حذف معيار بنجاح' }
      format.json { head :no_content }
    end
  end

  private
    def check_privs
      if !(current_user.is_admin?)
        respond_to do |format|
          format.html { redirect_to '/', alert: 'Insufficient Privileges..' } unless current_user.is_admin?
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_criterion
      @criterion = Criterion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterion_params
      params.require(:criterion).permit(:description, :is_active, :category_id)
    end
end

RoR/scoring-isdb/app/helpers/criterions_helper.rb
module CriterionsHelper
end

RoR/scoring-isdb/app/views/criterions/_form.html.erb
<%= simple_form_for @criterion, :html => { :class => "form-horizontal criterion" } do |f| %>

    <% if @criterion.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@criterion.errors.count, "error") %> prohibited this criterion from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @criterion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :description, label: "الوصف", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@criterion[:description]) %>
  </div>

  <div class="control-group">
    <%= f.label :category_id, label: "الفئة", :class => 'control-label' %>
    <div class="controls">
      <% @categories = Category.all.order(:id) %> 
      <%= f.collection_select :category_id, @categories , :id, :description, {prompt: "اختر فئة"}, :class => 'form-control' %>
    </div>
    <%= error_span(@criterion[:category_id]) %>
  </div>

  <div class="control-group">
    <%= f.label :criterion_type, label: "Type", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :criterion_type, :class => 'form-control' %>
    </div>
    <%= error_span(@criterion[:criterion_type]) %>
  </div>

  <div class="row">  
    <div class="funkyradio funkyradio-info pull-right">
        <%= f.check_box :is_active, :id => 'submit' %>
        <%= f.label :is_active, "فعال؟", :for => "submit" %>
        <%= error_span(@criterion[:is_active]) %>
    </div>
  </div> 

  <br/>
  <div class="row">
    <%= f.submit "حفظ", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              criterions_path, :class => 'btn btn-default' %>
  </div>

<% end %>

RoR/scoring-isdb/app/views/criterions/edit.html.erb
<%- model_class = Criterion -%>
<div class="page-header">
  <h1>تعديل معيار</h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/criterions/index.html.erb
<%- model_class = Criterion -%>
<div class="jumbotron">
    <h2 style="font-family: 'Droid Arabic Kufi';">المعايير</h2>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>الوصف</th>
      <th>الفئة</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @criterions.each do |criterion| %>
      <tr>
        <td><%= link_to criterion.description, criterion_path(criterion) %></td>
        <td><%= Category.find(criterion.category_id).description %></td>
        <td>
          <%= link_to  criterion_criterion_details_path(criterion), 
                      :class => 'btn btn-xs btn-default', :style => "font-family: 'Droid Arabic Kufi'; font-size: 13px;" do %>
           المقاييس<i class="fa fa-list-alt fa-lg"></i> 
          <% end %>
          &nbsp;&nbsp;&nbsp; 
          <%= link_to edit_criterion_path(criterion) do %>
          <i class="fa fa-edit fa-lg"></i>
          <% end %>
          &nbsp;&nbsp;&nbsp;  
          <%= link_to criterion_path(criterion),
                      :class => 'trash',
                      :method => :delete, 
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
                      <i class="fa fa-trash-o fa-lg"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_criterion_path,
            :class => 'btn btn-info'  do %>
            إضافة معييار جديد
        <i class="fa fa-plus-circle"></i>
<% end %> 

RoR/scoring-isdb/app/views/criterions/new.html.erb
<%- model_class = Criterion -%>
<div class="page-header">
  <h1>معيار جديد</h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/criterions/show.html.erb
<%- model_class = Criterion -%>
<div class="page-header">
  <h1>المعيار</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>الوصف:</strong></dt>
  <dd><%= @criterion.description %></dd>
  <dt><strong>الفئة:</strong></dt>
  <dd><%= Category.find(@criterion.category_id).description %></dd>
</dl>
<%= link_to "المقاييس",
            criterion_criterion_details_path(@criterion), 
                      :class => 'btn btn-info' %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              criterions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_criterion_path(@criterion), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              criterion_path(@criterion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>