RoR/scoring-isdb/config/routes.rb
Rails.application.routes.draw do    
  resources :grant_sectors

  match 'proposal_assessment_summaries/:proposal_id' => 'proposal_assessment_summaries#complete', :as => :complete_assessment, :via => :patch
  match 'proposal_assessment_summaries/:proposal_id/:user_id' => 'proposal_assessment_summaries#reset_assessment', :as => :reset_eval_assessment, :via => :patch
  match 'grants/:grant_id/reset_grant' => 'grants#reset_grant', :as => :reset_grant, :via => :patch
  
  match 'active_grant_sectors/all/gs_edit' => 'grant_sectors#gs_edit_all', :as => :gs_edit_all, :via => :get
  match 'active_grant_sectors/gs_all' => 'grant_sectors#gs_update_all', :as => :gs_update_all, :via => :put

  match 'proposals/select_winners' => 'proposals#update_selection', :as => :select_winners, :via => :put

  resources :funds
  resources :fund_sources
  resources :localities
  resources :proposals do
    resources :geographic_coverages, :budgets, :funds
    member do
      patch :complete
    end
  end

  resources :development_goals
  resources :sectors
  resources :provinces

  match 'home' => 'home#home_index', :as => :home, :via => :get
  match 'reports' => 'reports#index', :as => :reports, :via => :get
  match 'reports/statistics' => 'reports#statistics', :as => :reports_statistics, :via => :get
  match 'reports/assessments_mark_order' => 'reports#assessments_mark_order', :as => :reports_assessments_mark_order, :via => :get
  match 'reports/assessments_province_order' => 'reports#assessments_province_order', :as => :reports_assessments_province_order, :via => :get
  match 'reports/assessments_report/:proposal_id' => 'reports#assessments_rep', :as => :assessments_rep, :via => :get

  devise_for :users, except: [:new, :update]
  devise_scope :user do
    get "users/sign_up", to: "users/registrations#new", as: "new_app_user"
    put "/app_users/:id", to: "users/registrations#update", as: "update_app_user"
    patch "/app_users/:id", to: "users/registrations#update"
  end 

  as :user do
    get "/users", to: "registrations#admin_index", as: "admin_users"
    post "/add_user", to: "registrations#create", as: "create_user"
    get "/users/new", to: "registrations#admin_new", as: "admin_new_user"
    get "/users/admin_edit/:id", to: "registrations#admin_edit", as: "admin_edit_user"
    get "/admin_users/:id", to: "registrations#admin_show", as: "show_user"
    put "/users/:id", to: "registrations#update", as: "update_user"
    patch "/users/:id", to: "registrations#update"
    
  end

  resources :grants do
    member do
      patch :close
    end
  end

  resources :assessments 
  
  resources :categories
  resources :criterions do
    resources :criterion_details 
  end
  
  match 'e_assessments/edit/:proposal_id' => 'assessments#edit_all', :as => :edit_all, :via => :get 

  match 'e_assessments/update_all' => 'assessments#update_all', :as => :update_all, :via => :put 

  match 'users/:id/add_proposal' => 'proposals#add_proposal', :as => :add_proposal, :via => :post

  match 'proposals/:id' => 'proposals#update', :as => :add_geographic_coverage, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_budget, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_fund, :via => :post

  

  root to: "home#home_index"

  get '*a', :to => "home#home_index"

end

RoR/scoring-isdb/app/models/assessment.rb
class Assessment < ActiveRecord::Base
  has_many :proposals
  belongs_to :criterion
  has_many :assessment_criterion_details, :dependent => :destroy
  has_many :criterion_details, :through => :assessment_criterion_details

  accepts_nested_attributes_for :assessment_criterion_details, 
                                :reject_if => :all_blank

  def self.close(p_proposal_id, p_current_user_id)
    calc_mark=0.0
    l_mark=0.0
    @criterions=Criterion.where("criterion_type='E'")
      @criterions.each do |criterion|
        current_proposal=Proposal.find(p_proposal_id)
        l_weight=CriterionDetail.select('weight').where("criterion_id=?",criterion.id).first.weight
        if criterion.id==1
          l_mark=l_weight*(Proposal.least_budget(current_proposal.sector_id).to_f/current_proposal.proposal_budget)
        #####################
        elsif criterion.id==3
          direct_budget_count=Budget.where("proposal_id=? and cost_type='D'",p_proposal_id).count(:id)
          if direct_budget_count>=5
            l_mark=1
          elsif direct_budget_count==4
            l_mark=2
          elsif direct_budget_count<=3
            l_mark=3
          end
        #####################          
        elsif criterion.id==4
          indirect_budget_percentage=Budget.where("proposal_id=? and cost_type='I'",p_proposal_id).sum(:cost)/current_proposal.proposal_budget
          if indirect_budget_percentage>=0.05
            l_mark=1
          elsif indirect_budget_percentage>=0.03 and indirect_budget_percentage<0.05
            l_mark=2
          elsif indirect_budget_percentage>=0.01 and indirect_budget_percentage<0.03
            l_mark=3
          else
            l_mark=0
          end
        #####################
        elsif criterion.id==6
          provinces_number=Locality.select('distinct localities.id').joins(:geographic_coverages).where("geographic_coverages.proposal_id=?",current_proposal.id).count(:id)
          all_wb=Locality.select('distinct localities.id').joins(:geographic_coverages).where("geographic_coverages.proposal_id=? and locality_category='W'",current_proposal.id).count(:id)
          all_gaza=Locality.select('distinct localities.id').joins(:geographic_coverages).where("geographic_coverages.proposal_id=? and locality_category='G'",current_proposal.id).count(:id)
          national=Locality.select('distinct localities.id').joins(:geographic_coverages).where("geographic_coverages.proposal_id=? and locality_category='N'",current_proposal.id).count(:id)
          
          if provinces_number==1
           l_mark=1
          elsif provinces_number>=2 and provinces_number<=6
            l_mark=2
          elsif (all_wb>0 and all_gaza==0) or (all_wb==0 and all_gaza>0)
            l_mark=3
          elsif (all_wb>0 and all_gaza>0) or (national>0)
            l_mark=4
          else
            l_mark=0
          end
        #####################            
        elsif criterion.id==7
          l_mark=l_weight*(current_proposal.proposal_areas.to_f/Proposal.most_areas)
        #####################        
        elsif criterion.id==9
          geographic_coverages=Locality.joins(:geographic_coverages).where("geographic_coverages.proposal_id=?",current_proposal.id)
          poverty_sum=geographic_coverages.joins(:province).sum(:poverty_mapping)
          poverty_count=geographic_coverages.joins(:province).count
          l_mark=(poverty_sum/poverty_count) unless poverty_count==0              
        #####################
        elsif criterion.id==18
          if current_proposal.development_goal_id.nil?
            l_mark=0
          else
            l_mark=l_weight
          end
        #####################
        elsif criterion.id==20  
          beneficiaries_sum=GeographicCoverage.joins(:locality).where("proposal_id=?",current_proposal.id).sum(:beneficiaries_number)
          population_sum=GeographicCoverage.joins(:locality).where("proposal_id=?",current_proposal.id).sum(:population)
          percent=(beneficiaries_sum.to_f/population_sum) * 100
          
          if percent<21 and percent>=0
            l_mark=2
          elsif percent<41 and percent>=21
            l_mark=4
          elsif percent<61 and percent>=41
            l_mark=6
          elsif percent<81 and percent>=61
            l_mark=8
          elsif percent<=100 and percent>=81
            l_mark=10
          else
            l_mark=0
          end
        #####################
        elsif criterion.id==22
          l_mark=l_weight*(current_proposal.short_term_work_opportunities.to_f/Proposal.most_short_term_work_opportunities)
        #####################        
        elsif criterion.id==23
          l_mark=l_weight*(current_proposal.long_term_work_opportunities.to_f/Proposal.most_long_term_work_opportunities)
        end

        calc_mark=l_mark.round(2)
        current_assessment=Assessment.where("proposal_id=? and criterion_id=? and user_id=?",current_proposal.id, criterion.id, p_current_user_id).first
        current_assessment.update_attribute(:mark, calc_mark)   
    end 
    sum=Assessment.where("proposal_id=? and user_id=?",p_proposal_id, p_current_user_id).sum(:mark)
    @proposal_assessment_summary=ProposalAssessmentSummary.where("proposal_id=? and user_id=?", p_proposal_id, p_current_user_id).first
    @proposal_assessment_summary.update_attribute(:is_assessed, true)
    @proposal_assessment_summary.update_attribute(:total_mark, sum)
  end

end

RoR/scoring-isdb/app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy, :criteriondetailsassessments, :edit_all, :update_all]
  skip_before_filter :verify_authenticity_token
  before_action :check_privs
  respond_to :html, :json, :js

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
  end

  def criteriondetailsassessments
    @assessment = Assessment.where("proposal_id=? and criterion_id=19",params[:proposal_id])
    @assessment_criterion_details = @assessment.assessment_criterion_details
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: 'Assessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # GET /assessments/all/edit
  def edit_all
    proposal_id=params[:proposal_id]
    # @assessments_s1 = Assessment.where("criterion_id in (18) and proposal_id=? and user_id=?", proposal_id, current_user.id).order(:category_id, :criterion_id)    
    # 6,7, removed from s2
    @assessments_s2 = Assessment.where("criterion_id in (8,10) and proposal_id=? and user_id=?", proposal_id, current_user.id).order(:category_id, :criterion_id)    
    @assessments_s3 = Assessment.where("criterion_id in (11,12,13,14,15,16,17,21) and proposal_id=? and user_id=?", proposal_id, current_user.id).order(:category_id, :criterion_id)
    @assessments_s4 = Assessment.where("criterion_id in (2,5)   and proposal_id=? and user_id=?", proposal_id, current_user.id).order(:category_id, :criterion_id)  
    @assessments_s5 = Assessment.where("criterion_id in (17) and proposal_id=? and user_id=?", proposal_id, current_user.id).order(:category_id, :criterion_id)
    @assessments_s6 = Assessment.where("criterion_id in (19) and proposal_id=? and user_id=?", proposal_id, current_user.id).order(:category_id, :criterion_id)
  
    @assessment_criterion_details=AssessmentCriterionDetail.all
  end

  # PUT /assessments/all
  def update_all
    params["assessment"].keys.each do |id|
      @assessment = Assessment.find(id.to_i)
    #   put params['assessment'].values
    #   Assessment.update(params['assessment'].keys, params['assessment'].values)
    end
    Assessment.update(params['assessment'].keys, params['assessment'].values) unless params['assessment'].values==nil
    
    respond_to do |format|
      format.html { redirect_to edit_all_path(@assessment.proposal_id), notice: 'Assessment was successfully updated.'  }
      # format.html { render :edit_all, status: :ok, location: @assessment }
      format.js
    end
  end

  private
    def check_privs
      if !(current_user.is_eval?) or current_user.blank?
        respond_to do |format|
          format.html { redirect_to '/', alert: 'Insufficient Privileges..' } unless current_user.is_eval?
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      if params[:id].present?
        @assessment = Assessment.find(params[:id])
      else
        @assessment = Assessment.where("proposal_id=? and criterion_id=19",params[:proposal_id])
      end


    end

    def user_params(id)
      params.require(:assessment).fetch(id).permit(:mark, :proposal_id, :category_id, :criterion_id, :criterion_detail_id, :assessment_criterion_detail, :criterion_detail_ids => [])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
     def assessment_params
      params.require(:assessment).permit(:mark, :proposal_id, :category_id, :criterion_id, :assessment_criterion_detail, :criterion_detail_ids => [])
     end

     def assessment_criterion_detail_params
      params.require(:assessment_criterion_detail).permit(:mark, :criterion_detail_id, :assessment_id, :criterion_detail_ids => [])
     end
end

RoR/scoring-isdb/app/helpers/assessments_helper.rb
module AssessmentsHelper
end

RoR/scoring-isdb/app/views/assessments/_h1.html.erb
<div id="h1_div">
    <% ac_t1=Assessment.where("proposal_id=? and user_id=? and mark is null and criterion_id in (10,18)",@@proposal_id,current_user.id).count(:criterion_id) 
      fa_t1 = ac_t1>=1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
    %>
   	<i class="fa <%= fa_t1 %> fa-lg pull-left"></i>          
</div>

RoR/scoring-isdb/app/views/assessments/_h2.html.erb
<div id="h2_div">
    <% ac_t2=Assessment.where("proposal_id=? and user_id=? and mark is null and criterion_id in (8)",@@proposal_id,current_user.id).count(:criterion_id) 
      fa_t2 = ac_t2>=1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
    %>
    <i class="fa <%= fa_t2 %> fa-lg text-success pull-left"></i></h3>
</div>

RoR/scoring-isdb/app/views/assessments/_h3.html.erb
<div id="h3_div">
    <% ac_t3=Assessment.where("proposal_id=? and user_id=? and mark is null and criterion_id in (11,12,13,14,15,16,21)",@@proposal_id,current_user.id).count(:criterion_id) 
      fa_t3 = ac_t3>=1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
    %>
    <i class="fa <%= fa_t3 %> fa-lg text-success pull-left"></i></h3>
</div>

RoR/scoring-isdb/app/views/assessments/_h4.html.erb
<div id="h4_div">
    <% ac_t4=Assessment.where("proposal_id=? and user_id=? and mark is null and criterion_id in (2,5)",@@proposal_id,current_user.id).count(:criterion_id) 
      fa_t4 = ac_t4>=1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
    %>
    <i class="fa <%= fa_t4 %> fa-lg text-success pull-left"></i>
</div>

RoR/scoring-isdb/app/views/assessments/_h5.html.erb
<div id="h5_div">
  <% ac_t5=Assessment.where("proposal_id=? and user_id=? and mark is null and criterion_id in (17)",@@proposal_id,current_user.id).count(:criterion_id) 
    fa_t5 = ac_t5>=1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
  %>
  <i class="fa <%= fa_t5 %> fa-lg text-success pull-left"></i>
    
</div>

RoR/scoring-isdb/app/views/assessments/_h6.html.erb
<div id="h6_div">
<% ac_t6=AssessmentCriterionDetail.where("assessment_criterion_details.assessment_id=(select b.id from assessments b where b.proposal_id=? and b.criterion_id=19 and b.user_id=?)",@@proposal_id, current_user.id).sum(:mark)
                        fa_t6 = ac_t6<1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
                      %>
<i class="fa <%= fa_t6 %> fa-lg text-success pull-left"></i>
</div>

RoR/scoring-isdb/app/views/assessments/edit.html.erb
<%- model_class = Assessment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/assessments/edit_all.html.erb
<%= form_for :assessment, :url => update_all_path, :remote => true, :html => { :method => :put, :class => 'form-horizontal',role: 'form' } do %>
            <% 
              grant_id=Grant.active_grant_id
              @@proposal_id=params[:proposal_id]
              @proposal=Proposal.find(@@proposal_id)
              proposal_assessment_summary=ProposalAssessmentSummary.where("proposal_id=? and user_id=?", @@proposal_id, current_user.id).first
              @@i=0
            
              if proposal_assessment_summary.is_assessed
                @@view_only=true
              else
                @@view_only=false
              end
            %>
            <div class="jumbotron">
                <h2><i class="fa fa-check-square-o"></i> تقييم مقترح مؤسسة <b><%= @proposal.executive_organization %></b></h2>
            </div>
            <div style="font-size: 27px;">  
              <% unless grant_id==-1%>
                <strong>المنحة: </strong><%= Grant.find(grant_id).description %>
              <% end %>
            </div>
<% if 1==2 %> 
<div name="header" class="panel panel-info">
    <div class="panel-heading clickable">
        <% ac_t1=Assessment.where("proposal_id=? and user_id=? and mark is null and criterion_id in (10,18)",@@proposal_id,current_user.id).count(:criterion_id) 
          fa_t1 = ac_t1>=1 ? "fa-calendar-times-o text-danger":"fa-calendar-check-o text-success"
        %>
        <h3 class="panel-title"><span class="clickable"><i class="fa fa-minus"></i></span>
            تقييم المعلومات العامة للمقترح</h3><%= render :partial => 'h1' %> 
    </div> 
    <div class="panel-body">
          <div class="row">
            <div class="col-xs-3" >
              اسم المشروع
            </div>
            <div class="col-xs-6">
              <%= @proposal.project_name %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xs-3" style="font-family: 'Droid Arabic Kufi';" >
              اسم القطاع
            </div>
            <div class="col-xs-6">
              <%= Sector.find(@proposal.sector_id).programme %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xs-3" >
              خلفية ومبررات المشروع
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.project_background) %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xs-3" style="font-family: 'Droid Arabic Kufi';" >
              مدة تنفيذ المشروع (بالأشهر)
            </div>
            <div class="col-xs-6">
              <%= @proposal.project_period %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xs-3" style="font-family: 'Droid Arabic Kufi';" >
              هدف/ أهداف المشروع التنموية
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.project_aim) %>
            </div>
          </div> 
          <hr> 
          <div class="row">
            <div class="col-xs-3" style="font-family: 'Droid Arabic Kufi';" >
              الأهداف التنموية التي يعمل على تحقيقها (حسب الخطة التنموية الوطنية)
            </div>
            <div class="col-xs-6">
              <%= DevelopmentGoal.find(@proposal.development_goal_id).description %>
            </div>
          </div> 
          <hr>                      
      <table class="table table-condensed table-hover table-bordered">
        <tr>
          <th class="bg-success" style="text-align:center">المعيار</th>
          <th class="bg-success" style="text-align:center">المقياس</th>
        </tr>
          <!--  -->
           <% 
            @@current_assessments=@assessments_s1
          %>
          <%= render :partial => 'assess' %>
          <!--  -->
      </table>
    </div>
  </div>
  <% end %>

  <div name="header" class="panel panel-info">
        <div class="panel-heading clickable">
            <h3 class="panel-title"><span class="clickable"><i class="fa fa-minus"></i></span>
                تقييم الانكشاف</h3><%= render :partial => 'h2' %>  
        </div>
        <div class="panel-body">
          <div>
            <%= render :partial => 'geographic_coverages/index' %> 
          </div>  
          <hr>  
          <table class="table table-condensed table-hover table-bordered">
            <tr>
              <th class="bg-success" style="text-align:center">المعيار</th>
              <th class="bg-success" style="text-align:center">المقياس</th>
            </tr>
            <!--  -->
            <% 
              @@current_assessments=@assessments_s2
            %>
            <%= render :partial => 'assess' %> 
            <!--  -->
          </table>
      </div>
  </div>

  <div name="header" class="panel panel-info">
        <div class="panel-heading clickable panel-collapsed">
            <h3 class="panel-title"><span class="clickable"><i class="fa fa-minus"></i></span>
                تقييم جودة المقترح</h3><%= render :partial => 'h3' %>
        </div> 
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-3" >
              جهات ذات علاقة (مشاركة في التنفيذ) 
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.joint_ventures) %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xs-3" >
              خبرة المؤسسة في مشاريع مشابهة
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.organization_experience) %>
            </div>
          </div>
          <hr>
            <table class="table table-condensed table-hover table-bordered">
            <tr>
              <th class="bg-success" style="text-align:center">المعيار</th>
              <th class="bg-success" style="text-align:center">المقياس</th>
            </tr>
          <!--  -->
          <% 
            @@current_assessments=@assessments_s3
          %>
          <%= render :partial => 'assess' %> 
          <!--  -->
          </table>
      </div>
  </div>

  <div name="header" class="panel panel-info">
        <div class="panel-heading clickable panel-collapsed">
            <h3 class="panel-title"><span class="clickable"><i class="fa fa-minus"></i></span>
                تقييم الكفاءة المالية
              </h3><%= render :partial => 'h4' %>
        </div> 
        <div class="panel-body">
          <div>
            <%= render :partial => 'funds/index' %> 
          </div> 
          <div>
            <%= render :partial => 'budgets/index' %> 
          </div> 
          <div class="row">
            <div class="col-xs-3" >
              استدامة تشغيل المشروع ونتائجه
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.project_sustainability) %>
            </div>
          </div>
          <hr>
         <table class="table table-condensed table-hover table-bordered">
            <tr>
              <th class="bg-success" style="text-align:center">المعيار</th>
              <th class="bg-success" style="text-align:center">المقياس</th>
            </tr>
          <!--  -->
          <% 
            @@current_assessments=@assessments_s4
          %>
          <%= render :partial => 'assess' %> 
          <!--  -->
          </table>
    </div>
  </div>

  <% if 1==2 %>
  <div name="header" class="panel panel-info">
        <div class="panel-heading clickable panel-collapsed">
            <h3 class="panel-title"><span class="clickable"><i class="fa fa-minus"></i></span>
                تقييم جهة التنفيذ المقترحة</h3><%= render :partial => 'h5' %>
        </div> 
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-3" >
              جهات ذات علاقة (مشاركة في التنفيذ) 
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.joint_ventures) %>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-xs-3" >
              خبرة المؤسسة في مشاريع مشابهة
            </div>
            <div class="col-xs-6">
              <%= simple_format(@proposal.organization_experience) %>
            </div>
          </div>
          <hr>
          <table class="table table-condensed table-hover table-bordered">
            <tr>
              <th class="bg-success" style="text-align:center">المعيار</th>
              <th class="bg-success" style="text-align:center">المقياس</th>
            </tr>
          <!--  -->
          <% 
            @@current_assessments=@assessments_s5
          %>
          <%= render :partial => 'assess' %> 
          <!--  -->
          </table>
      </div>
  </div>
  <% end %>

  <div name="header" class="panel panel-info"> 
        <div class="panel-heading clickable panel-collapsed">
          <h3 class="panel-title"><span class="clickable"><i class="fa fa-minus"></i></span>
                تقييم الآثار المتوقعة لتنفيذ المشروع</h3><%= render :partial => 'h6' %>
        </div>
        <div class="panel-body">
         <table class="table table-condensed table-hover table-bordered">
            <tr>
              <th class="bg-success" style="text-align:center">المعيار</th>
              <th class="bg-success" style="text-align:center">المقياس</th>
            </tr>
            <!--  -->
            <% 
              @@current_assessments=@assessments_s6
            %>
            <%= render :partial => 'assess' %> 
            <!--  -->
          </table>  
      </div>
  </div>

  <div class="actions pull-left">
      <%= submit_tag 'حفظ', :name => "submit_button", :class => 'btn btn-info', :remote => true, :style => 'display: none;' %> 

      <%= link_to 'رجوع', proposals_path, :class => 'btn btn-default' %>

      <% if current_user.is_eval? %> 
        <%= link_to "معاينة المقترح", proposal_path(@proposal.id), :target => "_blank", :class => 'btn btn-info' %>

        <%  @proposal_assessment_summary=ProposalAssessmentSummary.where("proposal_id=? and user_id=?", @proposal.id,  current_user.id).first
            if !(@proposal_assessment_summary.is_assessed) %>
        <%= link_to complete_assessment_path(@proposal.id), :class => 'btn btn-danger', method: :patch, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirmassesscomplete", :default => 'Are you sure?')) } do %>
                      تأكيد عملية التقييم<i style="opacity: 0.5;" class="fa fa-check-square-o"></i>
                    <% end %>
        <% end %>

      <% end %>   
  </div>

  <div class="panel panel-info" style="position:fixed; padding:2px; text-align: center; left:17px; top: 68px; font-size= 20px;">
                    <div class="panel-heading">
                        <h3 class="panel-title" style="height: 30px;">
                            المجموع <%= render :partial => 'sum' %></h3>
                    </div>
  </div> 
<% end %>

RoR/scoring-isdb/app/views/assessments/index.html.erb
<%- model_class = Assessment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:mark) %></th>
      <th><%= model_class.human_attribute_name(:grant_id) %></th>
      <th><%= model_class.human_attribute_name(:applicant_id) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:criterion_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        
        <td><%= link_to assessment.id, assessment_path(assessment) %></td>
        <td><%= assessment.mark %></td>
        <td><%= assessment.grant_id %></td>
        <td><%= assessment.applicant_id %></td>
        <td><%= assessment.category_id %></td>
        <td><%= assessment.criterion_id %></td>
        <td><%=l assessment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_assessment_path(assessment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      assessment_path(assessment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_assessment_path,
            :class => 'btn btn-primary' %>