RoR/scoring-isdb/config/routes.rb
Rails.application.routes.draw do    
  resources :grant_sectors

  match 'proposal_assessment_summaries/:proposal_id' => 'proposal_assessment_summaries#complete', :as => :complete_assessment, :via => :patch
  match 'proposal_assessment_summaries/:proposal_id/:user_id' => 'proposal_assessment_summaries#reset_assessment', :as => :reset_eval_assessment, :via => :patch
  match 'grants/:grant_id/reset_grant' => 'grants#reset_grant', :as => :reset_grant, :via => :patch
  
  match 'active_grant_sectors/all/gs_edit' => 'grant_sectors#gs_edit_all', :as => :gs_edit_all, :via => :get
  match 'active_grant_sectors/gs_all' => 'grant_sectors#gs_update_all', :as => :gs_update_all, :via => :put

  match 'proposals/select_winners' => 'proposals#update_selection', :as => :select_winners, :via => :put

  resources :funds
  resources :fund_sources
  resources :localities
  resources :proposals do
    resources :geographic_coverages, :budgets, :funds
    member do
      patch :complete
    end
  end

  resources :development_goals
  resources :sectors
  resources :provinces

  match 'home' => 'home#home_index', :as => :home, :via => :get
  match 'reports' => 'reports#index', :as => :reports, :via => :get
  match 'reports/statistics' => 'reports#statistics', :as => :reports_statistics, :via => :get
  match 'reports/assessments_mark_order' => 'reports#assessments_mark_order', :as => :reports_assessments_mark_order, :via => :get
  match 'reports/assessments_province_order' => 'reports#assessments_province_order', :as => :reports_assessments_province_order, :via => :get
  match 'reports/assessments_report/:proposal_id' => 'reports#assessments_rep', :as => :assessments_rep, :via => :get

  devise_for :users, except: [:new, :update]
  devise_scope :user do
    get "users/sign_up", to: "users/registrations#new", as: "new_app_user"
    put "/app_users/:id", to: "users/registrations#update", as: "update_app_user"
    patch "/app_users/:id", to: "users/registrations#update"
  end 

  as :user do
    get "/users", to: "registrations#admin_index", as: "admin_users"
    post "/add_user", to: "registrations#create", as: "create_user"
    get "/users/new", to: "registrations#admin_new", as: "admin_new_user"
    get "/users/admin_edit/:id", to: "registrations#admin_edit", as: "admin_edit_user"
    get "/admin_users/:id", to: "registrations#admin_show", as: "show_user"
    put "/users/:id", to: "registrations#update", as: "update_user"
    patch "/users/:id", to: "registrations#update"
    
  end

  resources :grants do
    member do
      patch :close
    end
  end

  resources :assessments 
  
  resources :categories
  resources :criterions do
    resources :criterion_details 
  end
  
  match 'e_assessments/edit/:proposal_id' => 'assessments#edit_all', :as => :edit_all, :via => :get 

  match 'e_assessments/update_all' => 'assessments#update_all', :as => :update_all, :via => :put 

  match 'users/:id/add_proposal' => 'proposals#add_proposal', :as => :add_proposal, :via => :post

  match 'proposals/:id' => 'proposals#update', :as => :add_geographic_coverage, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_budget, :via => :post
  match 'proposals/:id' => 'proposals#update', :as => :add_fund, :via => :post

  

  root to: "home#home_index"

  get '*a', :to => "home#home_index"

end

RoR/scoring-isdb/app/models/grant.rb
class Grant < ActiveRecord::Base
	has_many :proposals

  validates_presence_of :description, :message => "الرجاء تعبئة حقل وصف المنحة"
  validates_presence_of :budget, :message => "الرجاء تعبئة حقل ميزانية المنحة"
  validates_presence_of :closing_at, :message => "الرجاء تعبئة حقل تاريخ انتهاء تقديم الطلبات"
  validates_presence_of :starting_at, :message => "الرجاء تعبئة حقل تاريخ بدء تقديم الطلبات"

  public
    def self.active_grant_id
       # grant_id=Grant.where("is_active=true and closed_at is null").last.id
       grant_id=Grant.where("is_active=true").last.id
       return grant_id
    rescue
       return -1
    end
    def is_selection_done?
      self.is_selection_done
    end

  # protected
    def closed?
      !closed_at.blank?
    end

    def proposal_period?
      Date.current>=starting_at and Date.current<=closing_at  
    end

    def evaluation_period?
      closing_at<Date.current and closed_at.blank?
    end
end

RoR/scoring-isdb/app/controllers/grants_controller.rb
class GrantsController < ApplicationController
  before_action :set_grant, only: [:show, :edit, :update, :destroy, :close, :reset_grant]
  before_action :check_privs

  def reset_grant
    @grant.update_attribute(:closed_at, nil)
    # redirect_to grants_path, notice: "تمت العملية بنجاح"
    # redirect_to assessments_rep_path(proposal_id), notice: "تمت العملية بنجاح"
    respond_to do |format|
      if @grant.save
        format.html { redirect_to grants_path, notice: 'تمّ تعديل منحة بنجاح' }
        format.json { render :show, status: :ok, location: @grant }
      else
        format.html { render :edit }
        format.json { render json: @grant.errors, status: :unprocessable_entity }
      end
    end
  end

  def close
    grant_id=Grant.active_grant_id
    if grant_id=@grant.id
      assessments_in_progress=ProposalAssessmentSummary.joins(:proposal).where("proposal_assessment_summaries.user_id != -1 and proposals.grant_id=? and (proposal_assessment_summaries.is_assessed is null or proposal_assessment_summaries.is_assessed=false)",grant_id)
      unless !(assessments_in_progress.blank?)
        @proposals=Proposal.where("grant_id=? and is_submitted",@grant.id).order(:id)
        @proposals.each do |proposal|
          # Calculating Assessments
          Assessment.close(proposal.id, -1)
          l_evals_no=ProposalAssessmentSummary.select(:user_id).distinct.where("user_id != -1").count
          l_avg_man_mark=ProposalAssessmentSummary.where("proposal_id=? and user_id != -1",proposal.id).sum(:total_mark)/(l_evals_no)  unless l_evals_no==0 
          puts "l_avg_man_mark  >>  ", l_avg_man_mark
          l_sys_mark=ProposalAssessmentSummary.where("proposal_id=? and user_id = -1",proposal.id).first.total_mark
          puts "l_sys_mark  >>  ", l_sys_mark
          l_avg_mark=l_avg_man_mark+l_sys_mark
          proposal.update_attribute(:average_mark, l_avg_mark.round(2))
        end  
        @grant.update_attribute(:closed_at, Time.now) 
        redirect_to grants_path, notice: "تم إغلاق المنحة والاحتساب النهائي لتقييم المقترحات"
      else
        redirect_to grants_path, alert: "هناك مقترحات قيد التقييم"
      end
    end #check grant_id
  end

  # GET /grants
  # GET /grants.json
  def index
    @grants = Grant.all.order('id desc')
  end

  # GET /grants/1
  # GET /grants/1.json
  def show

  end

  # GET /grants/new
  def new
    @grant = Grant.new
  end

  # GET /grants/1/edit
  def edit
  end

  # POST /grants
  # POST /grants.json
  def create
    if Grant.active_grant_id==-1
      @grant = Grant.new(grant_params)
      respond_to do |format|
        if @grant.save
          grant_id=@grant.id
          sectors=Sector.all.order(:id)
          sectors.each do |sector|
            @grant_sector=GrantSector.new
            @grant_sector.grant_id=grant_id
            @grant_sector.sector_id=sector.id
            @grant_sector.percentage=sector.percentage
            @grant_sector.save
          end  
          format.html { redirect_to @grant, notice: 'تمّ إضافة منحة جديدة بنجاح' }
          format.json { render :show, status: :created, location: @grant }
        else
          format.html { render :new }
          format.json { render json: @grant.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to grants_path, alert: 'توجد منحة فعالة!! .. لا يمكن إضافة منحة جديدة'
    end  
  end

  # PATCH/PUT /grants/1
  # PATCH/PUT /grants/1.json
  def update
    respond_to do |format|
      if @grant.update(grant_params)
        format.html { redirect_to grants_path, notice: 'تمّ تعديل منحة بنجاح' }
        format.json { render :show, status: :ok, location: @grant }
      else
        format.html { render :edit }
        format.json { render json: @grant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grants/1
  # DELETE /grants/1.json
  def destroy
    @grant.destroy
    respond_to do |format|
      format.html { redirect_to grants_url, notice: 'تمّ حذف منحة بنجاح' }
      format.json { head :no_content }
    end
  end

  private
    def check_privs
      if !(current_user.is_admin?)
        respond_to do |format|
          format.html { redirect_to '/', alert: 'Insufficient Privileges..' } unless current_user.is_admin?
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_grant
      @grant = Grant.find(params[:id])
    rescue
      @grant = Grant.find(params[:grant_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grant_params
      params.require(:grant).permit(:description, :is_active, :budget, :closing_at, :starting_at, :closed_at, :is_selection_done)
    end

end

RoR/scoring-isdb/app/helpers/grants_helper.rb
module GrantsHelper
end

RoR/scoring-isdb/app/views/grants/_form.html.erb
<%= simple_form_for @grant, :html => { :class => "form-horizontal grant" } do |f| %>
    <% if @grant.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">خطأ:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @grant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :description, :label => "وصف المنحة", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@grant[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :budget, :label => "الميزانية", :class => 'control-label' %>
    <div class="input-group">
      <%= f.text_field :budget, :type => :number, :class => 'form-control' %>
      <span class="input-group-addon"><i class="fa fa-usd"></i></span>
    </div>
    <%= error_span(@grant[:budget]) %>
  </div>
<div class="row">
  <div class="col-md-6">
  <div class="control-group">
    <%= f.label :starting_at, :label => "بدء موعد تقديم المقترحات", :class => 'control-label' %>
    <div class="input-group">
      <%= f.text_field :starting_at, :class => 'form-control datepicker input-small', "data-behaviour" => 'datepicker', :type => 'text' %>
      <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
    </div>
    <%= error_span(@grant[:starting_at]) %>
  </div>
</div>
<div class="col-md-6">
  <div class="control-group">
    <%= f.label :closing_at, :label => "آخر موعد تقديم المقترحات", :class => 'control-label' %>
    <div class="input-group">
      <%= f.text_field :closing_at, :class => 'form-control datepicker input-small', "data-behaviour" => 'datepicker', :type => 'text' %>
      <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
    </div>
    <%= error_span(@grant[:closing_at]) %>
  </div>
</div>
</div>
<% if @grant.persisted? %>
  <div class="row">
    <div class="col-md-6">
    <div class="funkyradio funkyradio-info">
      <%= f.check_box :is_active, :id => 'enable_submit' %>
      <%= f.label :is_active, "المنحة فعالة؟", :for => "enable_submit" %>
      <%= error_span(@grant[:is_active]) %>
    </div> 
    </div>
  </div>
  <% end %>
<br/>
<%= f.submit nil, value: "حفظ", :class => 'btn btn-info' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            grants_path, :class => 'btn btn-default' %>

<% end %>

RoR/scoring-isdb/app/views/grants/edit.html.erb
<%- model_class = Grant -%>
<div class="page-header">
  <h1>تعديل منحة</h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/grants/index.html.erb
<%- model_class = Grant -%>
<div class="jumbotron">
    <h2><i class="fa fa-university"></i> المنح</h2>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>الوصف</th>
      <th>الميزانية</th>
      <th>تاريخ بدء تقديم المقترحات</th>
      <th>تاريخ انتهاء تقديم المقترحات</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @grants.each do |grant| %>
      <tr>

        <td><%= link_to grant.id, grant_path(grant) %></td>
        <td><%= grant.description %></td>
        <td><%= grant.budget %></td>
        <td><%= grant.starting_at %></td>
        <td><%= grant.closing_at %></td>
        <td>
          <%= link_to edit_grant_path(grant) do %>
          <i class="fa fa-edit fa-lg"></i>
          <% end %>
          &nbsp;&nbsp;&nbsp; 
          <% props=Proposal.where("grant_id=?", grant.id)
             props_size=props.size
          if (props_size==0)
          %> 

          <%= link_to grant_path(grant),
                      :class => 'trash',
                      :method => :delete, 
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
                      <i class="fa fa-trash-o fa-lg"></i>
          <% end %>
          <% end %>
        </td>

        <td>
          <% if !(grant.closed?) and (grant.evaluation_period?) and grant.is_active and (props_size!=0)%>
            <%= link_to close_grant_path(grant),
              :class => 'btn btn-danger btn-xs',
              method: :patch, 
              :data => { :confirm => t('.confirmgrantdel', :default => t("helpers.links.confirmgrantdel", :default => 'Are you sure?')) } do %>
              <i class="fa fa-chain-broken fa-lg"></i> إغلاق ملف التقييم 
            <% end %>
          <% else %>
            <% if current_user.is_admin? and grant.closed? %>
              <%= link_to reset_grant_path(grant.id),
                      :class => 'text-danger',
                      :method => :patch, 
                      :data => { :confirm => t('.confirmgrantreset', :default => t("helpers.links.confirmgrantreset", :default => 'Are you sure?')) } do %>
                      <i class="fa fa-undo fa-lg"></i>
              <% end %><% end %>
          <% end %>
        </td>


      </tr>
    <% end %>
  </tbody>
</table

<br>     

<%= link_to new_grant_path,
            :class => 'btn btn-info'  do %>
            تعريف منحة جديدة
        <i class="fa fa-plus-circle fa-lg"></i>
<% end %>        

RoR/scoring-isdb/app/views/grants/new.html.erb
<%- model_class = Grant -%>
<div class="page-header">
  <h1>إضافة منحة جديدة</h1>
</div>
<%= render :partial => 'form' %>

RoR/scoring-isdb/app/views/grants/show.html.erb
<%- model_class = Grant -%>
<div class="page-header">
  <h1>المنحة</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>الوصف:</strong></dt>
  <dd><%= @grant.description %></dd>
  <dt><strong>الميزانية:</strong></dt>
  <dd>$<%= @grant.budget %></dd>
  <dt><strong>بدء موعد تقديم المقترحات:</strong></dt>
  <dd><%= @grant.starting_at %></dd>
  <dt><strong>آخر موعد لتقديم المقترحات:</strong></dt>
  <dd><%= @grant.closing_at %></dd>
  <dt><strong>فعالة:</strong></dt>
  <dd><%= @grant.is_active? ? "نعم" : "لا" %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              grants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_grant_path(@grant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              grant_path(@grant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>